title: afeng0007
description: afeng0007's blog
author: afeng0007
logo: /static/img/avatar.png
github: https://github.com/ashutosh2k12
about: Freelance developer

baseurl: "http://afeng0007.github.io/"
url: "http://afeng0007.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
